# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a3edf3ae5590528133ac2eb9254bf3f3075ca30a546b5e63db0ac4e9dd6ee92a9aed88500d988bd88cde00c1fe9ae3c61522254f0c572fd098c9bf06b264fe3

test:
  secret_key_base: dd44c5da50295c37965065bacd119c6428c082319ab1c1e121244bcb0c5c3bf2d68cde64f0e9d5288dcb2d6690e47679b43591fff972200ab219215d89d52a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
